// Actions
export {attack, dash, disengage, dodge, fall, help, knockOut as 'knock-out', knockOutEffect as 'knock-out-effect', ready, search, squeeze, stabilize, study, utilize} from './modern/actions/actionBatch1.mjs';
export {hide, hideEffect as 'hide-effect'} from './modern/actions/hide.mjs';
// Barbarian
export {brutalStrike as 'brutal-strike', sunderingBlow as 'sundering-blow'} from './modern/classFeatures/barbarian/brutalStrike.mjs';
export {dangerSense as 'danger-sense'} from './modern/classFeatures/barbarian/dangerSense.mjs';
export {divineFury as 'divine-fury', divineFuryAttack as 'divine-fury-attack', fanaticalFocus as 'fanatical-focus', frenzy} from './modern/classFeatures/barbarian/subclassFeatures.mjs';
export {extendRage, keepRage} from './modern/classFeatures/barbarian/rage.mjs';
export {fastMovement as 'fast-movement'} from './modern/classFeatures/barbarian/fastMovement.mjs';
export {feralInstinct as 'feral-instinct'} from './modern/classFeatures/barbarian/feralInstinct.mjs';
export {indomitableMight as 'indomitable-might'} from './modern/classFeatures/barbarian/indomitableMight.mjs';
export {persistentRage as 'persistent-rage'} from './modern/classFeatures/barbarian/persistentRage.mjs';
export {primalKnowledge as 'primal-knowledge'} from './modern/classFeatures/barbarian/primalKnowledge.mjs';
export {recklessAttack as 'reckless-attack'} from './modern/classFeatures/barbarian/recklessAttack.mjs';
export {relentlessRage as 'relentless-rage'} from './modern/classFeatures/barbarian/relentlessRage.mjs';
export {rageOfTheGods as 'rage-of-the-gods', rageOfTheGodsEffect as 'rage-of-the-gods-effect'} from './modern/classFeatures/barbarian/rageOfTheGods.mjs';
export {powerOfTheWilds as 'power-of-the-wilds', powerOfTheWildsLion as 'power-of-the-wilds-lion', powerOfTheWildsRam as 'power-of-the-wilds-ram'} from './modern/classFeatures/barbarian/wildHeart.mjs';
export {unarmoredDefenseBarbarian as 'unarmored-defense-barbarian'} from './modern/classFeatures/barbarian/unarmoredDefense.mjs';
export {warriorOfTheGods as 'warrior-of-the-gods'} from './modern/classFeatures/barbarian/warriorOfTheGods.mjs';
export {batteringRoots as 'battering-roots', branchesOfTheTree as 'branches-of-the-tree', lifeGivingForce as 'life-giving-force', travelAlongTheTree as 'travel-along-the-tree', vitalityOfTheTree as 'vitality-of-the-tree'} from './modern/classFeatures/barbarian/worldTree.mjs';
// Bard
export {bardicInspiration as 'bardic-inspiration', bardicInspirationEffect as 'bardic-inspiration-effect'} from './modern/classFeatures/bard/bardicInspiration.mjs';
export {combatInspiration as 'combat-inspiration', dazzlingFootwork as 'dazzling-footwork', leadingEvasion as 'leading-evasion'} from './modern/classFeatures/bard/danceFeatures.mjs';
export {beguilingMagic as 'beguiling-magic', mantleOfInspiration as 'mantle-of-inspiration'} from './modern/classFeatures/bard/glamourFeatures.mjs';
export {countercharm} from './modern/classFeatures/bard/countercharm.mjs';
export {mantleOfMajesty as 'mantle-of-majesty', mantleOfMajestyCommand as 'mantle-of-majesty-command', unbreakableMajesty as 'unbreakable-majesty', unbreakableMajestyEffect as 'unbreakable-majesty-effect'} from './modern/classFeatures/bard/majestyFeatures.mjs';
export {inspiringMovement as 'inspiring-movement', tandemFootwork as 'tandem-footwork'} from './modern/classFeatures/bard/danceReactions.mjs';
export {cuttingWords as 'cutting-words'} from './modern/classFeatures/bard/cuttingWords.mjs';
export {peerlessSkill as 'peerless-skill'} from './modern/classFeatures/bard/peerlessSkill.mjs';
export {fontOfInspiration as 'font-of-inspiration', jackOfAllTrades as 'jack-of-all-trades', superiorInspiration as 'superior-inspiration', wordsOfCreation as 'words-of-creation'} from './modern/classFeatures/bard/coreFeatures.mjs';
// Cleric
export {blessedHealer as 'blessed-healer'} from './modern/classFeatures/cleric/blessedHealer.mjs';
export {channelDivinity as 'channel-divinity-cleric'} from './modern/classFeatures/cleric/channelDivinity.mjs';
export {blessingOfTheTrickster as 'blessing-of-the-trickster'} from './modern/classFeatures/cleric/blessingOfTheTrickster.mjs';
export {coronaOfLight as 'corona-of-light', coronaOfLightEffect as 'corona-of-light-effect'} from './modern/classFeatures/cleric/coronaOfLight.mjs';
export {radianceOfTheDawn as 'radiance-of-the-dawn'} from './modern/classFeatures/cleric/radianceOfTheDawn.mjs';
export {wardingFlare as 'warding-flare', improvedWardingFlare as 'improved-warding-flare'} from './modern/classFeatures/cleric/wardingFlare.mjs';
export {discipleOfLife as 'disciple-of-life'} from './modern/classFeatures/cleric/discipleOfLife.mjs';
export {divineIntervention as 'divine-intervention'} from './modern/classFeatures/cleric/divineIntervention.mjs';
export {guidedStrike as 'guided-strike'} from './modern/classFeatures/cleric/guidedStrike.mjs';
export {preserveLife as 'preserve-life'} from './modern/classFeatures/cleric/preserveLife.mjs';
export {warPriest as 'war-priest'} from './modern/classFeatures/cleric/warPriest.mjs';
export {divineStrike as 'blessed-strikes-divine-strike'} from './modern/classFeatures/cleric/divineStrike.mjs';
export {greaterDivineIntervention as 'greater-divine-intervention', greaterDivineInterventionRest as 'greater-divine-intervention-rest'} from './modern/classFeatures/cleric/greaterDivineIntervention.mjs';
export {improvedBlessedStrikes as 'improved-blessed-strikes'} from './modern/classFeatures/cleric/improvedBlessedStrikes.mjs';
export {potentSpellcasting as 'blessed-strikes-potent-spellcasting'} from './modern/classFeatures/cleric/potentSpellcasting.mjs';
// Druid
export {archdruid} from './modern/classFeatures/druid/archdruid.mjs';
export {circleForms as 'circle-forms', lunarForm as 'lunar-form'} from './modern/classFeatures/druid/circleForms.mjs';
export {circleOfTheLandSpells as 'circle-of-the-land-spells'} from './modern/classFeatures/druid/circleOfTheLandSpells.mjs';
export {cosmicOmen as 'cosmic-omen', cosmicOmenActive as 'cosmic-omen-active'} from './modern/classFeatures/druid/cosmicOmen.mjs';
export {elementalFuryPotentSpellcasting as 'elemental-fury-potent-spellcasting'} from './modern/classFeatures/druid/elementalFury.mjs';
export {landsAid as 'lands-aid'} from './modern/classFeatures/druid/landsAid.mjs';
export {elementalFuryPrimalStrike as 'elemental-fury-primal-strike'} from './modern/classFeatures/druid/primalStrike.mjs';
export {moonlightStep as 'moonlight-step'} from './modern/classFeatures/druid/moonlightStep.mjs';
export {naturesSanctuary as 'natures-sanctuary', naturesSanctuaryTemplate as 'natures-sanctuary-template'} from './modern/classFeatures/druid/naturesSanctuary.mjs';
export {starryForm as 'starry-form', starryFormActive as 'starry-form-active'} from './modern/classFeatures/druid/starryForm.mjs';
export {wildCompanion as 'wild-companion'} from './modern/classFeatures/druid/wildCompanion.mjs';
export {wildResurgence as 'wild-resurgence'} from './modern/classFeatures/druid/wildResurgence.mjs';
export {wildShape as 'wild-shape', wildShapeActive as 'wild-shape-active'} from './modern/classFeatures/druid/wildShape.mjs';
export {wrathOfTheSea as 'wrath-of-the-sea', wrathOfTheSeaOngoing as 'wrath-of-the-sea-ongoing'} from './modern/classFeatures/druid/wrathOfTheSea.mjs';
// Fighter
export {groupRecovery as 'group-recovery'} from './modern/classFeatures/fighter/groupRecovery.mjs';
export {heroicWarrior as 'heroic-warrior'} from './modern/classFeatures/fighter/heroicWarrior.mjs';
export {knightlyEnvoy as 'knightly-envoy'} from './modern/classFeatures/fighter/knightlyEnvoy.mjs';
export {secondWind as 'second-wind'} from './modern/classFeatures/fighter/secondWind.mjs';
export {studiedAttacks as 'studied-attacks'} from './modern/classFeatures/fighter/studiedAttacks.mjs';
export {tacticalMind as 'tactical-mind'} from './modern/classFeatures/fighter/tacticalMind.mjs';
// Items
export {healersKit as 'healers-kit'} from './modern/items/healersKit.mjs';
// Monster Features
export {ghoulClaw as 'ghoul-claw', goblinBossRedirectAttack as 'goblin-boss-redirect-attack', vampireBite as 'vampire-bite', vampireMistyEscape as 'vampire-misty-escape'} from './modern/monsterFeatures/monsterBatch1.mjs';
// Monk
export {heightenedFocus as 'heightened-focus', perfectFocus as 'perfect-focus', disciplinedSurvivor as 'disciplined-survivor', superiorDefense as 'superior-defense'} from './modern/classFeatures/monk/focusFeatures.mjs';
export {deflectAttacks as 'deflect-attacks'} from './modern/classFeatures/monk/deflectAttacks.mjs';
export {empoweredStrikes as 'empowered-strikes'} from './modern/classFeatures/monk/empoweredStrikes.mjs';
export {martialArts as 'martial-arts'} from './modern/classFeatures/monk/martialArts.mjs';
export {monksFocus as 'monks-focus'} from './modern/classFeatures/monk/monksFocus.mjs';
export {selfRestoration as 'self-restoration'} from './modern/classFeatures/monk/selfRestoration.mjs';
export {slowFall as 'slow-fall'} from './modern/classFeatures/monk/slowFall.mjs';
export {stunningStrike as 'stunning-strike'} from './modern/classFeatures/monk/stunningStrike.mjs';
export {unarmoredDefenseMonk as 'unarmored-defense-monk'} from './modern/classFeatures/monk/unarmoredDefense.mjs';
export {unarmoredMovement as 'unarmored-movement'} from './modern/classFeatures/monk/unarmoredMovement.mjs';
export {uncannyMetabolism as 'uncanny-metabolism'} from './modern/classFeatures/monk/uncannyMetabolism.mjs';
// Paladin
export {auraOfCourage as 'aura-of-courage'} from './modern/classFeatures/paladin/auraOfCourage.mjs';
export {auraOfProtection as 'aura-of-protection'} from './modern/classFeatures/paladin/auraOfProtection.mjs';
export {layOnHands as 'lay-on-hands'} from './modern/classFeatures/paladin/layOnHands.mjs';
// Ranger
export {beguilingTwist as 'beguiling-twist'} from './modern/classFeatures/ranger/beguilingTwist.mjs';
export {dreadAmbusher as 'dread-ambusher', shadowyDodge as 'shadowy-dodge', stalkersFlurry as 'stalkers-flurry'} from './modern/classFeatures/ranger/gloomStalker.mjs';
export {exceptionalTraining as 'exceptional-training', naturesVeil as 'natures-veil', otherworldlyGlamour as 'otherworldly-glamour', preciseHunter as 'precise-hunter', shareSpells as 'share-spells'} from './modern/classFeatures/ranger/miscFeatures.mjs';
export {favoredEnemy as 'favored-enemy', foeSlayer as 'foe-slayer', relentlessHunter as 'relentless-hunter', tireless} from './modern/classFeatures/ranger/coreFeatures.mjs';
export {primalCompanion as 'primal-companion', primalCompanionStrike as 'primal-companion-strike'} from './modern/classFeatures/ranger/primalCompanion.mjs';
export {umbralSight as 'umbral-sight'} from './modern/classFeatures/ranger/umbralSight.mjs';
// Rogue
export {cunningAction as 'cunning-action'} from './modern/classFeatures/rogue/cunningAction.mjs';
export {cunningStrike as 'cunning-strike'} from './modern/classFeatures/rogue/cunningStrike.mjs';
export {elusive} from './modern/classFeatures/rogue/elusive.mjs';
export {envenomWeapons as 'envenom-weapons', envenomPoison as 'envenom-poison', magicalAmbush as 'magical-ambush'} from './modern/classFeatures/rogue/subclassFeatures.mjs';
export {psionicPower as 'psionic-power', psychicBlades as 'psychic-blades'} from './modern/classFeatures/rogue/psionicPower.mjs';
export {psychicVeil as 'psychic-veil', rendMind as 'rend-mind', soulBlades as 'soul-blades'} from './modern/classFeatures/rogue/soulknife.mjs';
export {spellThief as 'spell-thief'} from './modern/classFeatures/rogue/spellThief.mjs';
export {reliableTalent as 'reliable-talent'} from './modern/classFeatures/rogue/reliableTalent.mjs';
export {slipperyMind as 'slippery-mind'} from './modern/classFeatures/rogue/slipperyMind.mjs';
export {sneakAttack as 'sneak-attack'} from './modern/classFeatures/rogue/sneak-attack.mjs';
export {steadyAim as 'steady-aim'} from './modern/classFeatures/rogue/steadyAim.mjs';
export {strokeOfLuck as 'stroke-of-luck'} from './modern/classFeatures/rogue/strokeOfLuck.mjs';
export {uncannyDodge as 'uncanny-dodge'} from './modern/classFeatures/rogue/uncannyDodge.mjs';
// Warlock
export {agonizingBlast as 'eldritch-invocations-agonizing-blast'} from './modern/classFeatures/warlock/agonizingBlast.mjs';
export {awakenedMind as 'awakened-mind'} from './modern/classFeatures/warlock/awakenedMind.mjs';
export {createThrall as 'create-thrall', thrallBonus as 'thrall-bonus'} from './modern/classFeatures/warlock/createThrall.mjs';
export {giftOfTheProtectors as 'eldritch-invocations-gift-of-the-protectors', giftOfTheProtectorsProtected as 'gift-of-the-protectors-protected'} from './modern/classFeatures/warlock/giftOfTheProtectors.mjs';
export {pactOfTheChain as 'eldritch-invocations-pact-of-the-chain', magicalCunning as 'magical-cunning', oneWithShadows as 'eldritch-invocations-one-with-shadows'} from './modern/classFeatures/warlock/pactOfTheChain.mjs';
export {pactOfTheBlade as 'eldritch-invocations-pact-of-the-blade', pactOfTheBladeAttack as 'pact-of-the-blade-attack'} from './modern/classFeatures/warlock/pactOfTheBlade.mjs';
export {psychicSpells as 'psychic-spells'} from './modern/classFeatures/warlock/psychicSpells.mjs';
export {stepsOfTheFey as 'steps-of-the-fey'} from './modern/classFeatures/warlock/stepsOfTheFey.mjs';
export {thoughtShield as 'thought-shield'} from './modern/classFeatures/warlock/thoughtShield.mjs';
// Wizard
export {arcaneRecovery as 'arcane-recovery'} from './modern/classFeatures/wizard/arcaneRecovery.mjs';
export {memorizeSpell as 'memorize-spell'} from './modern/classFeatures/wizard/memorizeSpell.mjs';
// Feats
export {alert, archery, defense, dueling, greatWeaponFighting as 'great-weapon-fighting', heavyArmorMaster as 'heavy-armor-master', sharpshooter, speedy, thrownWeaponFighting as 'thrown-weapon-fighting'} from './modern/feats/featBatch1.mjs';
export {grappler, interception} from './modern/feats/featBatch2.mjs';
export {crusher, piercer, slasher} from './modern/feats/weaponMasteryFeats.mjs';
export {elementalAdeptA as 'elemental-adept-acid', elementalAdeptC as 'elemental-adept-cold', elementalAdeptF as 'elemental-adept-fire', elementalAdeptL as 'elemental-adept-lightning', elementalAdeptT as 'elemental-adept-thunder'} from './modern/feats/elementalAdept.mjs';
export {healer, protection} from './modern/feats/featBatch4.mjs';
export {telekineticShove as 'telekinetic-shove', unarmedFighting as 'unarmed-fighting', unarmedFightingUnarmedStrike as 'unarmed-fighting-unarmed-strike'} from './modern/feats/telekineticUnarmed.mjs';
export {savageAttacker as 'savage-attacker', tavernBrawler as 'tavern-brawler'} from './modern/feats/featBatch3.mjs';
// Species Features
export {dreadfulStrikes as 'dreadful-strikes', relentlessEndurance as 'relentless-endurance'} from './modern/speciesFeatures/orc.mjs';
export {celestialResistance as 'celestial-resistance', celestialRevelation as 'celestial-revelation', celestialRevelationActive as 'celestial-revelation-active', healingHands as 'healing-hands'} from './modern/speciesFeatures/aasimar.mjs';
// Spells
export {aid} from './modern/spells/aid.mjs';
export {auraOfVitality as 'aura-of-vitality', auraOfVitalityEffect as 'aura-of-vitality-effect'} from './modern/spells/auraOfVitality.mjs';
export {bane} from './modern/spells/bane.mjs';
export {banishingSmite as 'banishing-smite'} from './modern/spells/banishingSmite.mjs';
export {beaconOfHope as 'beacon-of-hope', beaconOfHopeHopeful as 'beacon-of-hope-hopeful'} from './modern/spells/beaconOfHope.mjs';
export {deathWard as 'death-ward', deathWardWarded as 'death-ward-warded'} from './modern/spells/deathWard.mjs';
export {guardianOfFaith as 'guardian-of-faith', guardianOfFaithDamage as 'guardian-of-faith-damage'} from './modern/spells/guardianOfFaith.mjs';
export {alterSelf as 'alter-self'} from './modern/spells/alterSelf.mjs';
export {animateDead as 'animate-dead', vitriolicSphere as 'vitriolic-sphere'} from './modern/spells/animateDead.mjs';
export {animateObjects as 'animate-objects'} from './modern/spells/animateObjects.mjs';
export {animalFriendship as 'animal-friendship', animalMessenger as 'animal-messenger', armsOfHadar as 'arms-of-hadar'} from './modern/spells/spellBatch4.mjs';
export {antilifeShell as 'antilife-shell', antilifeShellMove as 'antilife-shell-move'} from './modern/spells/antilifeShell.mjs';
export {armorOfAgathys as 'armor-of-agathys', armorOfAgathysArmor as 'armor-of-agathys-armor'} from './modern/spells/armorOfAgathys.mjs';
export {auraOfLife as 'aura-of-life', auraOfLifeAura as 'aura-of-life-aura', auraOfPurity as 'aura-of-purity', auraOfPurityAura as 'aura-of-purity-aura'} from './modern/spells/auraSpells.mjs';
export {arcaneVigor as 'arcane-vigor', blindnessDeafness as 'blindness-deafness', charmMonster as 'charm-monster', charmPerson as 'charm-person'} from './modern/spells/spellBatch1.mjs';
export {banishment, banishmentBanished as 'banishment-banished', blur, blurEffect as 'blur-effect'} from './modern/spells/spellBatch2.mjs';
export {bestowCurse as 'bestow-curse', bestowCurseAttackEffect as 'bestow-curse-attack-effect', bestowCurseDamageSource as 'bestow-curse-damage-source'} from './modern/spells/bestowCurse.mjs';
export {blight, calmEmotions as 'calm-emotions'} from './modern/spells/spellBatch3.mjs';
export {blink, blinkBlinking as 'blink-blinking', blinkBlinkedAway as 'blink-blinked-away'} from './modern/spells/blink.mjs';
export {burningHands as 'burning-hands', chillTouch as 'chill-touch', chromaticOrb as 'chromatic-orb'} from './modern/spells/chromaticOrb.mjs';
export {cacophonicShield as 'cacophonic-shield', cacophonicShieldSourceEffect as 'cacophonic-shield-source-effect'} from './modern/spells/cacophonicShield.mjs';
export {chainLightning as 'chain-lightning'} from './modern/spells/chainLightning.mjs';
export {circleOfPower as 'circle-of-power', circleOfPowerActive as 'circle-of-power-active'} from './modern/spells/circleOfPower.mjs';
export {cloudkill, cloudkillCloud as 'cloudkill-cloud', cloudkillSource as 'cloudkill-source'} from './modern/spells/cloudkill.mjs';
export {darkness} from './modern/spells/darkness.mjs';
export {deathArmor as 'death-armor', deathArmorEffect as 'death-armor-effect'} from './modern/spells/deathArmor.mjs';
export {destructiveWave as 'destructive-wave'} from './modern/spells/destructiveWave.mjs';
export {dragonsBreath as 'dragons-breath'} from './modern/spells/dragonsBreath.mjs';
export {eldritchBlast as 'eldritch-blast'} from './modern/spells/eldritchBlast.mjs';
export {hex, hexAttack as 'hex-attack'} from './modern/spells/hex.mjs';
export {mistyStep as 'misty-step', shield} from './modern/spells/mistyStep.mjs';
export {huntersMark as 'hunters-mark', huntersMarkSource as 'hunters-mark-source'} from './modern/spells/huntersMark.mjs';
export {guidance} from './modern/spells/guidance.mjs';
export {tollTheDead as 'toll-the-dead'} from './modern/spells/tollTheDead.mjs';
export {blindingSmite as 'blinding-smite'} from './modern/spells/blindingSmite.mjs';
export {bless} from './modern/spells/bless.mjs';
export {command, commandTurnStart as 'command-turn-start', commandGrovel as 'command-grovel'} from './modern/spells/command.mjs';
export {compelledDuel as 'compelled-duel', compelledDuelSource as 'compelled-duel-source', compelledDuelTarget as 'compelled-duel-target'} from './modern/spells/compelledDuel.mjs';
export {protectionFromEvilAndGood as 'protection-from-evil-and-good'} from './modern/spells/protectionFromEvilAndGood.mjs';
export {sanctuary, sanctuarySafe as 'sanctuary-safe'} from './modern/spells/sanctuary.mjs';
export {divineSmite as 'divine-smite'} from './modern/spells/divineSmite.mjs';
export {passWithoutTrace as 'pass-without-trace', passWithoutTraceAura as 'pass-without-trace-aura'} from './modern/spells/passWithoutTrace.mjs';
export {powerWordHeal as 'power-word-heal', powerWordKill as 'power-word-kill'} from './modern/spells/powerWords.mjs';
export {resistance, resistanceEffect as 'resistance-effect', synapticStatic as 'synaptic-static', thornWhip as 'thorn-whip'} from './modern/spells/resistance.mjs';
export {scorchingRay as 'scorching-ray'} from './modern/spells/scorchingRay.mjs';
export {searingSmite as 'searing-smite'} from './modern/spells/searingSmite.mjs';
export {spiritGuardians as 'spirit-guardians', spiritGuardiansDamage as 'spirit-guardians-damage'} from './modern/spells/spiritGuardians.mjs';
export {spiritualWeapon as 'spiritual-weapon'} from './modern/spells/spiritualWeapon.mjs';
export {shiningSmite as 'shining-smite'} from './modern/spells/shiningSmite.mjs';
export {staggeringSmite as 'staggering-smite'} from './modern/spells/staggeringSmite.mjs';
export {thunderousSmite as 'thunderous-smite'} from './modern/spells/thunderousSmite.mjs';
export {spikeGrowth as 'spike-growth', spikeGrowthSpikes as 'spike-growth-spikes'} from './modern/spells/spikeGrowth.mjs';
export {steelWindStrike as 'steel-wind-strike'} from './modern/spells/steelWindStrike.mjs';
export {sleetStorm as 'sleet-storm', sleetStormArea as 'sleet-storm-area'} from './modern/spells/sleetStorm.mjs';
export {summonAberration as 'summon-aberration', summonBeast as 'summon-beast', summonCelestial as 'summon-celestial', summonConstruct as 'summon-construct', summonDragon as 'summon-dragon', summonElemental as 'summon-elemental', summonFiend as 'summon-fiend', summonFey as 'summon-fey', summonUndead as 'summon-undead'} from './modern/spells/summonSpells.mjs';
export {teleport} from './modern/spells/teleport.mjs';
export {thunderwave, vampiricTouch as 'vampiric-touch'} from './modern/spells/thunderwave.mjs';
export {timeStop as 'time-stop', timeStopEffect as 'time-stop-effect'} from './modern/spells/timeStop.mjs';
export {trueStrike as 'true-strike', shockingGrasp as 'shocking-grasp'} from './modern/spells/trueStrike.mjs';
export {wish, wishStress as 'wish-stress', wishImmunity as 'wish-immunity'} from './modern/spells/wish.mjs';
export {zoneOfTruth as 'zone-of-truth'} from './modern/spells/zoneOfTruth.mjs';
export {wallOfFire as 'wall-of-fire', wallOfFireWall as 'wall-of-fire-wall'} from './modern/spells/wallOfFire.mjs';
export {wardingBond as 'warding-bond', wardingBondSource as 'warding-bond-source', wardingBondTarget as 'warding-bond-target'} from './modern/spells/wardingBond.mjs';
export {wrathfulSmite as 'wrathful-smite'} from './modern/spells/wrathfulSmite.mjs';
export {crusadersMantle as 'crusaders-mantle', crusadersMantleAura as 'crusaders-mantle-aura'} from './modern/spells/crusadersMantle.mjs';
export {heroism, heroismHeroic as 'heroism-heroic'} from './modern/spells/heroism.mjs';
